name: LyttleNavigation
description: Custom nametags plugin
version: '${projectVersion}'
main: com.lyttledev.lyttlenavigation.LyttleNavigation
api-version: '1.21'
authors:
  - LyttleDevelopment
  - ThatsATim
  - Stualyttle

depend:
  - packetevents

softdepend:
  - PlaceholderAPI

commands:
  lyttlenavigation:
    description: Admin command, mainly reload the config without the rest of the server
    permission: lyttlenavigation.lyttlenavigation